### ISSUE TITLE
User profile: State/Province enhancements

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#212] opened 2017-02-07 23:11 UTC
Feedback from round1 testing #185 - TC8

- [x] Request dropdown box to select State or Province based on Country (Canada and USA)
- [ ] For other countries where state/province is not applicable, may be just grey out the field and enable it only if Canada or USA are selected as country.

@joshi1983, please review this and update with design info if needed before assigning

**Comment by joshi1983** [comment] 2017-02-08 04:28
If new volunteers are expected to take aspects of this on, it should be broken down smaller because it may take some time to do.  Mind if I make separate issues?

Here's how I'm thinking to break the work down:
- Create a new region table in the database.
- Find a source of public domain or safe for our use-licence data that associates every "territory", "state", "province", "region" with their corresponding countries and find a way to represent that in our seed data files.
- Implement the UI changes requested from feedback using the data gathered and organised from the above tasks.

**Comment by stephanosm** [comment] 2017-02-08 12:45
looks good to me!

**Comment by Blandine-AA** [comment] 2017-02-08 19:04
Great! That's exactly the process... 
Please open separate issues, reference to this one, as it will make it easier to assign to the students.

**Comment by joshi1983** [comment] 2017-02-09 02:35
I created a couple issues for the data collection.  The UI changes I left out temporarily since the UI changes would be more understandable after the data is ready to use.

**Comment by joshi1983** [comment] 2017-03-12 02:04
I created #254 for the remaining UI work.  Better than the original suggestion of disabling the field for unsupported countries, it offers a way of letting the users still enter free text.  This gives the user more freedom when our options are too limited but still guides the user to match an existing item when appropriate.

**Comment by joshi1983** [comment] 2017-04-29 22:30
@Blandine-AA the first subtask is complete but do you still want the second part that hasn't been completed yet?

"For other countries where state/province is not applicable, may be just grey out the field and enable it only if Canada or USA are selected as country." ?

**Comment by Blandine-AA** [comment] 2017-05-03 14:50
@joshi1983 why shouldn't the second task not implemented?
Do we plan to support searches for "unsupported countries" using that field? If yes, then they should become supported. Right? Otherwise, they don't need the field and it should be disabled/greyed out.

**Comment by joshi1983** [comment] 2017-05-03 15:02
I didn't have a big reason to think the second subtask wasn't needed anymore.  I was just asking since it was 3 or 4 months since the issue was created and wanted to confirm that the second subtask was still important for someone to work on.  Lots was done for the issue since then and just wanted to make sure the requirement didn't change before someone invests time implementing it.

**Comment by Blandine-AA** [comment] 2017-05-03 15:07
I think it is still needed.

**Comment by joshi1983** [comment] 2017-05-04 00:27
The country list is huge at around 140 countries and most users will be picking from US or Canada for the next few months at least.  Are you ok with just hiding every country except US and Canada for now instead of disabling the region input?

**Comment by stephanosm** [comment] 2017-05-04 02:31
I think it is ok just hiding the countries for now.

**Comment by joshi1983** [comment] 2017-05-04 11:48
Based on @stephanosm and my opinion that hiding the countries that don't have region data was good, that's been done.

That change is deployed to:
[app.accesslocator.com](http://app.accesslocator.com)

**Comment by balraj18** [comment] 2017-06-06 03:14
I tested this issue and it is working exactly how it supposed to be. 
![image](https://cloud.githubusercontent.com/assets/25542570/26812211/64314026-4a44-11e7-83dc-e2b7b519765f.png)
how ever I found a little bug which is shown in second screen shot:-
![image](https://cloud.githubusercontent.com/assets/25542570/26812248/a075bfc6-4a44-11e7-8931-9580f37340ae.png)

the dropdown gets hide under the browser suggestion.

**Comment by intherightdirection** [comment] 2017-06-08 04:26
On testing for issue 254 as it is related to this issue and crosses over. I had tested multiple browsers, at different resolutions, computers, and full screen. 
In Firefox, Edge and IE this appears to work as expected, however I found issue in Chrome and Opera for United States drop down to select state. In both of these browsers, with a long list of states going off page, it does not allow you any way to scroll through states and are stuck to what can be displayed on screen. In the 3 previously mentioned browsers a scroll bar is provided most likely a default behavior for their user agents, and may need to specify what shows on screen or a method to scroll through? 
This is difficult to show in a screen shot, but if not clear, I can try.

**Comment by Blandine-AA** [comment] 2017-06-08 14:15
@joshi1983, I am not sure who implemented this (you or @brucelau-github). So, I am assigning to you for review at next meeting along with #254, and let me know if we move it to release 0.0.5 or if it can be fixed and tested for 0.0.4.

**Comment by joshi1983** [comment] 2017-06-08 14:20
I wasn't able to reproduce with Internet Explorer and I can't install Edge in Windows 8.1.  I wanted to test with Edge since that's what Balraj's screenshot is from.  I'll decide 0.0.4 or 0.0.5 Friday evening in the development meeting since it might be reproducable on one of the volunteer's laptops.

**Comment by joshi1983** [comment] 2017-06-10 18:58
Jared tried this in Edge on Windows 10 and wasn't able to reproduce the problem that Balraj ran into with the options getting overlapped by the city field.

I'm closing since this is very difficult to reproduce.  I'll make a new issue after getting more information from Balraj so his result isn't simply lost.

**Closed by joshi1983** 2017-06-10 18:58 UTC
Labels: Failed Testing, For next meeting review
