### ISSUE TITLE
Resend Verification Email Button

### ISSUE THREAD

**Issue by M4ttoF** [hhaccessibility/hhaccessibility.github.io#648] opened 2018-07-21 15:07 UTC
If user did not receive the email the first time they tried to reset their password, we should give them an option to resend the email

Here is a mockup from Hardik:
![image](https://user-images.githubusercontent.com/19508538/43095323-778673a6-8e83-11e8-989f-9e2cea3abdfb.png)

**Comment by joshi1983** [comment] 2018-07-23 17:10
During the meeting, I wasn't sure why we'd have 2 features for this.  @passionInfinite suggested having a separate Email recovery from password recovery feature.  I understand that there are 2 cases that we as developers need to manage:
1. User hasn't verified their email account yet.
2. User has verified their email account but forgot their password.

I still don't understand why we'd have two features that a user has to select from, though.  Why not have a feature that fits both cases?  The user enters his/her email address and we send the appropriate email for their case.  We can check the email_verification_time field of the corresponding user table to decide whether to send them a password reset email or another email verification email.

**Comment by M4ttoF** [comment] 2018-07-23 18:21
instead of making 2 features that do the same thing, I instead made it an option for the user to be able to resend the verification after they already complete the forgotten password page.

**Comment by joshi1983** [comment] 2018-07-26 11:43
I merged Matthew's latest changes for this issue and deployed them on https://app.accesslocator.com.  That seemed like a good improvement but there's a final part that would help this issue some more.

It would be nice to also send the email verification link instead of the password reset link when the email hasn't been verified for the specified email address.  @M4ttoF can you make a new pull request to make that server-side change?

**Comment by M4ttoF** [comment] 2018-08-03 12:57
changes were merged so I'm closing this issue

**Comment by joshi1983** [comment] 2018-08-04 17:02
I'm reopening to give @singlaneha2205 the opportunity to test this.  I encouraged the password recovery and email verification to be handled by the same link and form.  Neha, do you like the result?  It is on https://app.accesslocator.com?

**Comment by singlaneha2205** [comment] 2018-08-06 02:02
@joshi1983 I tested the above issue and was able to receive the mail to reset the password. The only issue is with the content of the mail received. The email address that I used was not confirmed earlier but the mail received was regarding the password reset which could be quite confusing. According to my view we should have a check here before sending out the mail. If the user account id is verified the mail can be the reset password but if the user account is not verified the mail should be regarding the account confirmation. For the time being I am failing the testing to discuss this with the team.

**Comment by joshi1983** [comment] 2018-08-06 17:52
I forgot to deploy Matthew's latest change for this.  @singlaneha2205 will it help if I delete some of your user accounts?  Are you creating new email accounts to test this?

**Comment by singlaneha2205** [comment] 2018-08-06 20:58
You can go ahead and delete the accounts but please do tell me what all are deleted.

**Comment by joshi1983** [comment] 2018-08-12 22:54
I deleted the following:
- singlaneha2205@gmail.com
- nsingla009@gmail.com

I noticed another account with your full name but didn't delete because you had answers associated with it.

Can you retest it now?

**Comment by singlaneha2205** [comment] 2018-08-14 18:42
@joshi1983 I tried testing the issue but I think there is problem with the appplication as I am not able to login neither I am able to sign up with the new email id. So for the time being I am marking it as testing failed

**Comment by M4ttoF** [comment] 2018-08-14 19:01
@singlaneha2205 currently there is an issue with with the service worker from #680 interacting with the captcha that I didn't see in testing. @joshi1983 can you undo the merge of the service worker as it seems to be interacting oddly with other parts of the app. After that the test can be redone.

**Comment by joshi1983** [comment] 2018-08-15 16:18
@M4ttoF the service worker changes aren't merged.  I temporarily deployed it roughly a week ago, though.

You may need to clear all cache from your browser to eliminate the effects of the service worker.  It looks like service workers stick around even after hitting CTRL+SHIFT+R.

Were you able to get the signup email, Neha?  I tested with a hotmail account just now and the processed ended with me not receiving the verification email.

**Comment by M4ttoF** [comment] 2018-08-15 16:27
Not only hard refresh the cache, I also had to do this to get rid of the service worker
![image](https://user-images.githubusercontent.com/19508538/44159776-78599a00-a086-11e8-86b6-a421740e79ed.png)
Also I just tested the registration with a temporary email and I was able to get the sign up message 
![image](https://user-images.githubusercontent.com/19508538/44159837-9d4e0d00-a086-11e8-98b1-e002d4dcf3bf.png)

**Comment by singlaneha2205** [comment] 2018-08-16 02:25
@M4ttoF I tested the above issue and it is working fine. I am able to signup a new email successfully and was able to use the account recovery flow successfully too.

**Comment by joshi1983** [comment] 2018-08-16 10:50
While testing for myself just now that the emails are received, I found a bug when submitting an account recovery form but merged a fix for it and tested that it worked on https://app.accesslocator.com.

I'm closing this issue because Neha and I tested and see no problems with this issue now.

**Closed by joshi1983** 2018-08-16 10:50 UTC
Labels: Tested Successfully
