### ISSUE TITLE
Mobile device:  clicks responsiveness for location's category 

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#527] opened 2018-03-06 22:04 UTC
This problem happens on mobile devices only and was found by @yashankit17 during testing on iPhone. I see the same problem testing on my Android phone.

When you click any category on the home page, you will see its description in the footer for the first click
and then on the second click you will be redirected to new page showing results of those category. The problem is that category description in the footer is only shown on the first click after that even if you click a different category, you will be redirected to new page directly and you won’t see any description after the first click.

Clicking once shows the description then automatically goes to the Search results page. sometimes it wors and doesn't go to the Search results page. Do we need a longer wait time?

After playing around selecting the location categories, I got this exception: https://drive.google.com/open?id=1B0y6Pk4oR3-ufg_VmEskQnL5jjpK4jG9

**Comment by joshi1983** [comment] 2018-06-10 02:06
@Henry-Hao I assigned this to you as per our gmail chat conversation.  Good luck.

**Comment by Henry-Hao** [comment] 2018-06-15 21:00
I think I may have solved this problem.
Add a variable ***previous_touched_target*** to store the previous clicked label.
For the mobiles, if the users click the label for the first time or click a label which is not the same as he clicked previously. The ***previous_touched_target*** will be updated. Then i use the function ***e.preventDefault()*** to prevent the default action of ***touchend*** event which is redirect to another page.
The page will be redirected only when the user touches the same label twice.
Hope this is a solution to this issue.

**Comment by joshi1983** [comment] 2018-06-15 21:51
I think the exception part of the issue description was handled in #555.  It looks like the same kind of problem.

**Comment by joshi1983** [comment] 2018-06-15 22:10
I'm struggling to reproduce the problem or maybe just understand it.  I tested on an Android tablet and Android phone and got the same results on both.

My experience is this:
1. Click any category.  
1. Wait up to 5 seconds.
1. Watch the results for that category show.

I wonder if you're seeing a delay and confusing that with the incorrect results of a different category.  Here's a sequence to illustrate:
1. Click Restaurant
1. Click Associations immediately after.  Rush to click it within a fraction of a second.
1. See location search results for Restaurant.  These results would show because they were being downloaded in the background while clicking Associations.

The delay isn't by design.  Computing the search results just doesn't happen faster than a second or two.

**Comment by joshi1983** [comment] 2018-10-22 04:56
I'm closing because the issue appears to not be an actual bug.  It is more of a user not knowing that a delay was intentional.

**Closed by joshi1983** 2018-10-22 04:56 UTC

**Comment by joshi1983** [comment] 2018-10-22 04:57
I'm closing because the issue appears to not be an actual bug.  It is more of a user not knowing that a delay was intentional.
