### ISSUE TITLE
Rating window is not showing completely on iPhone

### ISSUE THREAD

**Issue by yashankit17** [hhaccessibility/hhaccessibility.github.io#395] opened 2017-10-21 18:53 UTC
![990530cc-58de-49d6-8e80-4ee5efb31bd2](https://user-images.githubusercontent.com/32559887/31854962-030e029c-b66f-11e7-81e2-adc5ba3ff421.jpg)
 
Rating window is loading as in the picture initially and user have to slide the page or zoom out the page to see the complete window.

**Comment by Blandine-AA** [comment] 2017-10-23 16:33
@yashankit17, this is a duplicate of #325.

**Comment by joshi1983** [comment] 2017-10-23 16:40
@yashankit17 since it is a duplicate, please copy that image and your comments to #325 and close #395.

**Closed** 2017-10-23 19:07 UTC
Labels: Duplicate
