### ISSUE TITLE
User Profile : Layout and functionality

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#110] opened 2016-12-14 23:05 UTC
![user profile](https://cloud.githubusercontent.com/assets/20052162/21376737/7d5e457a-c705-11e6-9dee-054981c16304.jpg)

**Comment by joshi1983** [comment] 2016-12-18 17:36
I assigned this to Blandine because she needs to finish writing this issue before anyone can work on it.

**Comment by areebakamal** [comment] 2016-12-18 18:31
![6userprofile5](https://cloud.githubusercontent.com/assets/23005093/21295574/12936530-c526-11e6-83df-84d7252d2b63.jpg)

This will show if the user hasn't rated any buildings yet: 
![6userprofilev2 - copy](https://cloud.githubusercontent.com/assets/23005093/21295575/12968724-c526-11e6-9b69-4347dd22725a.jpg)

**Comment by joshi1983** [comment] 2016-12-18 18:53
The "Search Radius" being grouped with the user's home location can cause confusion.  If the search radius is to show on the profile, the search location text should show next to it instead of information about the user's home location.

There is an independent "search location" from where the user permanently lives.  The search location is what will be used in every search and with search radius to filter search results down to a circular region on Earth.  The home location is only used for displaying of comments.  Quite often, where the person is searching will be close to where he permanently lives.  These 2 locations are easily confused but since it was made clear in our meeting that both are needed, we'll have to be extra careful with how we explain that distinction to the user and anyone working on the project.

**Comment by Blandine-AA** [comment] 2016-12-21 03:40
- Rename "Search Radius" to "Distance"
- Change password should be a button as you will need to type your password twice for validation.

**Comment by joshi1983** [comment] 2017-01-01 19:38
I checked some of @Blandine-AA 's subtasks that look complete from Areeba and my changes to the profile.  @Blandine-AA you can review them at [app.accesslocator.com](http://app.accesslocator.com).

**Comment by Blandine-AA** [comment] 2017-01-01 20:27
Please rename "My reviewed Blogs"  to "My Reviews"

**Comment by Blandine-AA** [comment] 2017-01-04 16:37
I was thinking for the My Reviews button, that we should show the number of reviews in brackets like : 
"My Reviews (0)"

2 benefits for doing it:
1. The user knows immediately how many locations s-he reviewed
2. For the demo we don't need to add the "Under development" page :).

**Comment by joshi1983** [comment] 2017-01-04 17:11
That seems good to me.  

Since multiple reviews can be made by the same user on the same location, the number of reviews isn't the same as number of reviewed locations.  It may be more understandable to the end user to show number of reviewed locations.

**Comment by Blandine-AA** [comment] 2017-01-12 19:24
Got some initial feedback on this section:
![image](https://cloud.githubusercontent.com/assets/20052162/21904737/ad9d1336-d8d2-11e6-81f6-31c11e25048b.png)

**Issues:**
- Check boxes are too small
- Text is too small
- Extra space below the list of criteria 
- Can't close list

We will need to rediscuss the design to better reflect the initial proposal.

**Comment by joshi1983** [comment] 2017-01-15 17:56
The saving of profile information should work now.  The only part that won't save is the email address which needs more thought.

We want all email addresses confirmed and updating the email address in the current layout could switch from a confirmed address to an unconfirmed one without any confirmation step to check that the user is happy with that.

**Comment by joshi1983** [comment] 2017-01-16 23:43
@areebakamal , @Blandine-AA asked "why is it a check-mark all the time on the save button?" on #173.  Is it because saving is like saying that you're ok with all the changes?
![image](https://cloud.githubusercontent.com/assets/11838191/22002610/566cb75a-dc1b-11e6-8317-68d36a25bf33.png)

**Comment by stephanosm** [comment] 2017-01-17 01:57
I kinda like the check mark. It will even be better if it is without the check mark and on-click event it shows an animated check mark (indicating that this has been saved). This animation it could be 2-3 images of the check mark

**Comment by Blandine-AA** [comment] 2017-01-20 18:16
@joshi1983 , regarding the photo upload feature... 

Why having a message after uploading the picture? I Think it would be better to just have the profile page refreshed and the photo displayed. Unless there was and error processing the upload, then you would show an error message on the same Profile Photo Upload page and ask the user to try again!

If there has been unsaved changes to the page, you would remind the user that the changes will be saved at the same time as the photo.

**Comment by joshi1983** [comment] 2017-01-20 22:35
@Blandine-AA I guess it is a funny case but text saying that the upload succeeded might help a blind user know that it worked.  Even in that case, maybe going back to the profile is clear enough.

Having a test environment independent of the app.accesslocator.com wouldn't be a lot of extra work but maintaining it takes yet another 30 minutes out of an average of 4 hour for me per week.  Keep in mind how little time we have on a routine basis to work on this project.  Things like test deployment updates separate from monthly demo updates separate will have a significant effect on how much time remains on more permanent feature and bug fix work.

**Comment by Blandine-AA** [comment] 2017-01-21 04:02
@joshi1983 ,

I definitely understand the time constraint and hopefully we will get more help soon.

Regarding the test environment, I think that once it is cut-off, we don't need to maintain it, since it is meant to be tested as is, unless it is unusable. In that case, we just trash it and cut-off another one from a working app environment.

I don't really see the maintenance work that will be required. Please explain.

**Comment by areebakamal** [comment] 2017-01-27 02:53
I agree with @stephanosm for the check mark to appear after the user has clicked 'Save Profile'.

**Comment by areebakamal** [comment] 2017-01-27 03:05
![image](https://cloud.githubusercontent.com/assets/23005093/22359214/263a96ba-e413-11e6-9fa5-3ce07e8bf3b0.png)

I can make those changes in the current layout if we want to stick to the collapsible list idea.

**Comment by joshi1983** [comment] 2017-01-27 11:38
I'm leaning toward the rediscussion happening before implementing any changes on it.

As you increase the font size, expand the check boxes, add more space, be sure that you don't add a scrollbar or something weird to the Bathrooms question category.  Bathrooms has a lot more questions which take a lot more space than other question categories.

Maybe allowing for inconsistent heights for each section can help since the Bathrooms can just be much taller and Parking is much shorter and both of them have little blank space while also not having a vertical scrollbar.

**Comment by Blandine-AA** [comment] 2017-01-27 18:41
@areebakamal, I think it wouldn't hurt to investigate how to make this section work considering various feedback we have  on this issue.

**Comment by Blandine-AA** [comment] 2017-04-10 12:18
Update the profile, the rating and the advance search features to use the finalized accessibility criteria list of April 3rd, 2017.
[AccessLocator_Accessibility criteria checklist_Final_03April2017.pdf](https://github.com/hhaccessibility/hhaccessibility.github.io/files/909987/AccessLocator.-.accessibility.criteria.checklist-.Final.03April2017.pdf)

**Comment by joshi1983** [comment] 2017-04-12 11:37
@Blandine-AA that criteria list update happened roughly a week ago and can be seen at [app.accesslocator.com](http://app.accesslocator.com)

**Comment by joshi1983** [comment] 2018-11-12 11:39
I'm closing since all of this work has been completed a while ago.

A lot of different requirements were discussed here.  Newer issues such as #695 improved on the layout designs in this issue by moving infrequently accessed profile features to other pages.  We'll keep making new issues to cover changes so the issues can be sharper focused and easier to implement.

**Closed by joshi1983** 2018-11-12 11:39 UTC
