### ISSUE TITLE
Search result page: visualize search radius on Map

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#205] opened 2017-02-06 02:39 UTC
When viewing search results in the Map view, it would be nice to see a representation of the geographical search range over the map.  There is a blue marker on the search location but no representation of the search radius.

Map as it is now:
![image](https://cloud.githubusercontent.com/assets/11838191/22632690/a87c70e8-ebe9-11e6-9c36-c1508682d2d4.png)

Mockup of map with the proposed search range visualization:
![image](https://cloud.githubusercontent.com/assets/11838191/22632872/e9c70a08-ebea-11e6-91eb-7ad46c69ecd9.png)

All of the red markers should be inside the circle when it is working properly.  The mockup isn't perfect.

The mockup isn't centred well.  The blue marker should be in the centre of the circle.

There are various ways to this but watch out for the following:
- Clicking the red markers inside the visualized range must still navigate a user to that location's report.
- The zoom in and zoom out features with the + - buttons in the lower right corner should still work unless you have a strong reason to disable them.  The disk should appropriately expand and shrink as the zoom level changes.

The work on #205 will probably break down to the following tasks:
- [x] Find a similar feature on another website or in Google Maps documentation
- [x] Implement the change and test it in our project.

#205 is related to a broader issue #135 .

**Comment by Blandine-AA** [comment] 2017-02-06 14:56
I like the idea. 

Does this needs to be split in more than one issue or have tasks created to better track the features implemented and the completion of the work?

**Comment by joshi1983** [comment] 2017-02-06 15:29
@Blandine-AA this would probably start with trying to find a similar feature on another website or mentioned on Google.  The next step would be to implement a similar technique in our project.  I guess those are 2 subtasks of #205 but representing them as 2 separate github issues might be more confusing than it is worth. There won't be any code changes in finding a similar solution but there would be in implementing the change.  #205 is also already a little piece of #135.

**Comment by joshi1983** [comment] 2017-02-09 02:39
#101 is done now so all the red markers should fit inside the proposed circle.

**Comment by e1cerebro** [comment] 2017-02-17 23:41
What if the red marker is not within the search range specified by the user, it will fall outside the overlay.

**Comment by joshi1983** [comment] 2017-02-18 06:07
@e1cerebro your circle looked very good in our meeting.  It also looked like it should be roughly the size we'd want.  The way some of the red markers were out of the circle seemed like it had to be a bug in something but we had trouble getting a specific location that clearly had the wrong distance result.  

The one we looked at was called something like Ecole Catholique E.J but it looked roughly the right distance.

Can you try give me a specific location far to the East or West of your circle?

**Comment by e1cerebro** [comment] 2017-02-18 09:17
Ya, you could check "Forest Glade Community Centre". On the app the distance is 2.20km but am getting roughly 17km with google map.
![hjj](https://cloud.githubusercontent.com/assets/22207261/23092065/b17ca692-f588-11e6-91d6-160f4401c6f1.PNG)

**Comment by e1cerebro** [comment] 2017-02-18 09:31
So basically I was trying to compare with we have on this tabel
![er](https://cloud.githubusercontent.com/assets/22207261/23092136/f24e567e-f589-11e6-99d6-e6f61cdb1f92.PNG)
with what we have on google map below
![goo](https://cloud.githubusercontent.com/assets/22207261/23092142/2c2c3820-f58a-11e6-9e20-8d15e2ed911c.PNG)

So based on the data on out app, the difference in km between the two locations is like 2.36 km. But based on what we have on google map it should longer that 2.36

This is also what I have our map
![b](https://cloud.githubusercontent.com/assets/22207261/23092164/a3302bf2-f58a-11e6-9ccb-88991490462b.PNG)
POINT A=Constable John Atkinson Memorial Community Centre
POINT B= Forest Glade Community Centre

**Comment by joshi1983** [comment] 2017-02-18 15:21
@e1cerebro nice find.  I merged a fix to that distance calculation bug you uncovered.  Can you commit your current changes for the overlay and then pull latest and rebase?

The commands are documented at:
https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/git-commands

Your work looks very close to ready for a pull request.

**Comment by joshi1983** [comment] 2017-02-20 15:03
@e1cerebro 's changes were merged.  It looks good to me on app.accesslocator.com so I'm closing this issue.

Here is a screenshot from app.accesslocator.com:
![image](https://cloud.githubusercontent.com/assets/11838191/23130276/cf9c437c-f753-11e6-9054-a85b62a53074.png)

**Comment by Blandine-AA** [comment] 2017-02-27 13:48
Reopened for testing

**Comment by e1cerebro** [comment] 2017-03-07 20:56
**# These are the steps to test Issue-205:**

1. Navigate to the home page by clicking on the home link at the top of the page.

**HOW TO SEARCH:**
You can either follow step 2 to 4 or just step 5.

 **METHOD ONE:**
2. Enter the search address in the address text field.
3. Enter the search key word in the search keyword text field.
4. Click on the search button.
      OR
**METHOD TWO**
5. Click on the any of the location categories.
**Either of these two methods would take you to the Location Search Results:**

**VIEWING THE SEARCH RESULT ON MAP MODE**
6. Click on **map  button** on the upper right hand side of the page.

**TESTING THE SEARCH RADIUS**
7. If the search radius is not visible, try clicking on the zoom out icon on the map (It is placed on the lower right hand side of the map).
8. Check if all the points are within the radius.
9. Check if the blue marker is at the center of the map.
10. Finally click on each of the location markers and see if they will link you to the right page.

**Comment by areebakamal** [comment] 2017-03-14 01:17
Some of the remarks may not necessarily directly relate to this issue rather stem from it:

1) I feel like there should be a way to insert the radius while you are on the results page after search. I've zoomed out plenty as Chris suggested but I do not see a radius or a way to change it without visiting the Profile page. 
2) If the radius can only be changed on the profile page, there should be a search box on the profile page too. 
3) I feel like it's important to show the radius in whichever format because if the user entered a large radius on the profile page, he may never zoom out that much to ever make use of the feature. 
![image](https://cloud.githubusercontent.com/assets/23005093/23881391/913429ea-0830-11e7-94e9-7b1e61e35412.png)

The features directly related such as the blue marker appearing in the center of search radius through search box or category selection, and circle overlay of defined radius works well. 

RESULT: PASS.

**Comment by joshi1983** [comment] 2017-03-14 01:37
@areebakamal what do you think of having the radius determine the initial zoom level such that the full circle is always immediately visible so no one needs to zoom out for it?

You're correct that the profile page is the only place where you can update the radius for now.  How would you suggest selecting the search radius on the location search results page?  Any suggestion for how the input control might look or work?

One idea that comes to my mind is a little button that looks like http://fontawesome.io/icon/bullseye/ that switches on a radius resize mode and lets you adjust the radius with your mouse on the map.  When clicked, the radius would be set and the page would refresh so the location results show corresponding with the new radius.

Another little problem with the map is it is still possible to get the blue marker off the map if you zoom in enough which could be confusing.

**Comment by areebakamal** [comment] 2017-03-14 02:10
@joshi1983 
"the radius determine the initial zoom level"--  I think this is a good idea. Initial zoom should be dependent on the radius so that the entire circle overlay is visible initially.

I was thinking something like this:
![image](https://cloud.githubusercontent.com/assets/23005093/23882725/eacb4512-0838-11e7-959b-a802f82e79f4.png)
Where it says 50mi, we would put a text box there which displays the value as the user drags left or right and also gives the capability of just entered the radius number there. We can place this addition beside the table and map tabs and make it only visible on 'Map' view.

For the table view, it should simply be a text box near the top of the page, Enter radius: |___________|

**Comment by Blandine-AA** [comment] 2017-03-21 11:53
New issue #260 has been created to track the testing feedback for enhancement. Closing this one as the initial design is working as intended

**Closed by Blandine-AA** 2017-03-21 11:53 UTC
