### ISSUE TITLE
Create a new logo for AccessLocator

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#116] opened 2016-12-16 21:52 UTC
- [x] Create a new logo image
- [x] Upload a high resolution(over 1000 pixel height) raster or SVG version of the image to a comment on this issue
- [x] Scale a version to 16 by 16 pixels to verify that crucial details are still somewhat visible and for use as a favicon in the web application
- [x] Validate with JMCC

Be consistent with the website's colour scheme by using the same blue-green and gray.

**Comment by areebakamal** [comment] 2016-12-18 17:40
![logo4](https://cloud.githubusercontent.com/assets/23005093/21295251/10fc100c-c51f-11e6-8c11-7cb387154623.jpg)
![logo](https://cloud.githubusercontent.com/assets/23005093/21295252/10fe419c-c51f-11e6-95c6-9dca4854ad7a.jpg)
![logo2v1](https://cloud.githubusercontent.com/assets/23005093/21295253/11028bbc-c51f-11e6-9c73-f3c4c6fe4498.jpg)
![logo2v2](https://cloud.githubusercontent.com/assets/23005093/21295254/11065e54-c51f-11e6-9865-232c2aa231ef.jpg)
![logo2v3](https://cloud.githubusercontent.com/assets/23005093/21295255/110b2ba0-c51f-11e6-837d-924c364627ac.jpg)
![logo2v4](https://cloud.githubusercontent.com/assets/23005093/21295256/110e576c-c51f-11e6-8a8a-deeca0ec0b61.jpg)
![logo2v35](https://cloud.githubusercontent.com/assets/23005093/21295257/111a7498-c51f-11e6-9c81-4c6fa4370a83.jpg)
![logo3v1](https://cloud.githubusercontent.com/assets/23005093/21295258/111d2968-c51f-11e6-984f-ee806a50bb86.jpg)
![logo3v2](https://cloud.githubusercontent.com/assets/23005093/21295259/1120e896-c51f-11e6-8de9-1771e7a72f73.jpg)

**Comment by areebakamal** [comment] 2016-12-18 17:42
Once the logo is chosen, I can modify it according to need.

**Comment by joshi1983** [comment] 2016-12-18 18:00
The following looks best to me:
https://cloud.githubusercontent.com/assets/23005093/21295252/10fe419c-c51f-11e6-95c6-9dca4854ad7a.jpg

Mixing the accessible symbol into the logo seems like a pretty good idea but the way those logo images mix with the A and L letters looks like someone in a wheel chair crashed into a fence and can't get out.  Maybe there's a way to make the body of the disabled person subtly indicate the A and L.

The last one looks much too complicated.  Keep in mind point 3 in that list.
![image](https://cloud.githubusercontent.com/assets/11838191/21295381/e76446a8-c521-11e6-85cd-c6903a3dca3b.png)

**Comment by areebakamal** [comment] 2016-12-18 21:43
"looks like someone in a wheel chair crashed into a fence and can't get out." I can see that now! 😆

**Comment by Blandine-AA** [comment] 2016-12-19 01:09
Hi Areeba,

Great proposals so far... but I agree with Josh's comments. Also, the green color doesn't fit well with our current colors. Blue (blue-green as per Josh), Grey and white

I wouldn't put a specific disability as it will make it predominant and none of the disabilities are more important than the others.

If you could blend the person  with the A and L, it would be great. Also, smoother/curved border are better... I think!

**Comment by Blandine-AA** [comment] 2016-12-21 01:10
Here is a proposal I sketched.  

Areeba, you can draw it and see what it looks  like with the colors and proper ratio. I don't know what color to use for the head. So, I just put a question mark. Make your color proposals

![logo proposal](https://cloud.githubusercontent.com/assets/20052162/21373883/3af228ec-c6f0-11e6-9e7f-4c150f1a67ef.jpg)

**Comment by areebakamal** [comment] 2016-12-21 01:50
Ok I've made something somewhat similar. Was working on making the edges more crisp as I started off on low resolution unknowingly.

**Comment by areebakamal** [comment] 2016-12-21 01:52
![latest copy](https://cloud.githubusercontent.com/assets/23005093/21374640/1ad13228-c6f6-11e6-8107-cbaf720d3187.jpg)
![latest copyccc](https://cloud.githubusercontent.com/assets/23005093/21374641/1ad25f40-c6f6-11e6-9a99-6b39c9523317.jpg)
![latest copydfdfd](https://cloud.githubusercontent.com/assets/23005093/21374642/1ad9db26-c6f6-11e6-876e-a7ef1d75d18b.jpg)
![logo2vediteddd](https://cloud.githubusercontent.com/assets/23005093/21374643/1ada432c-c6f6-11e6-9182-3de244028026.jpg)

**Comment by Blandine-AA** [comment] 2016-12-21 01:59
Thanks Areeba, but it is not quite what I drew and the colors are off. The colors have to match the same Blue and Grey we have on the app.

What I drew has a person in the middle and the blue part is the A and the L is the grey part. The branches do not connect but they are close enough. Look at the way the curves work too.

Can you try to reproduce the sketch please? 

Thanks

**Comment by areebakamal** [comment] 2016-12-21 02:01
The same blue as in the color of the square boxes on the homepage?

**Comment by areebakamal** [comment] 2016-12-21 02:13
![design2](https://cloud.githubusercontent.com/assets/23005093/21375080/21569ae0-c6f9-11e6-9fe1-dff9cbb513b9.jpg)

**Comment by areebakamal** [comment] 2016-12-21 02:24
![latest copssssssy](https://cloud.githubusercontent.com/assets/23005093/21375318/a71f2268-c6fa-11e6-89fe-e488dc9bf5a8.jpg)

**Comment by Blandine-AA** [comment] 2016-12-21 03:01
Thanks Areeba, looks more like it!

Of course the sketch ratios will need to be adjusted as well as the alignment. But this extra work will be done only if we go with this idea.

Is the blue in the square boxes the same blue as in the pie-chart?
What if the A is Grey and the L blue?
What if we have the head colour more like the light blue we have  to show the location path on the home page?

Thanks,

**Comment by joshi1983** [comment] 2016-12-22 15:27
https://cloud.githubusercontent.com/assets/23005093/21375318/a71f2268-c6fa-11e6-89fe-e488dc9bf5a8.jpg looks good to me.  The colours look close enough that the site won't need to be tweaked much for them.

I guess when we make a final decision on a logo, you can smooth everything out.

**Comment by Blandine-AA** [comment] 2016-12-22 22:58
The problem I have with this one is that it is too chubby. I will not resize well if you want to make it small. I think we need something sleek and that can reduce well and not loose its meaning.

If https://cloud.githubusercontent.com/assets/23005093/21375080/21569ae0-c6f9-11e6-9fe1-dff9cbb513b9.jpg is properly resized to the proper ratio and centered I thing it will be good. Any other feedback?

**Comment by stephanosm** [comment] 2016-12-22 23:46
With positive criticism and a sense of humor I have to say Blandine's idea reminds me a Ninja!  The problem I see here is that the lines are too sharp. Also, the first thing you see, is a big X, and not very artistic. I like more this one as it is more clever, simple and elegant. Having said that, it still needs some work. Perhaps more smooth the edges or something, but it is closer to the one I believe it is the right one. We can also have 2 variations, one 3D-look for the web and one 2D.

https://cloud.githubusercontent.com/assets/23005093/21375318/a71f2268-c6fa-11e6-89fe-e488dc9bf5a8.jpg

**Comment by stephanosm** [comment] 2016-12-23 00:19
how about something like this? For the L use a brush style. You can also make it a bit  look more like an L and a check at the same time. I also recommend more bright colors like this logo which stand out. They don't have to be the exact same colors of the website because blue and green are basic colors. Another idea you can use Red for the dot (head). If you guys like the idea then Areeba can draw something like around this.

https://cloud.githubusercontent.com/assets/22602396/21444390/e0660d76-c87a-11e6-879a-683d4a0393ec.jpg

**Comment by Blandine-AA** [comment] 2016-12-23 01:39
The problem you have with my proposal is that the rendering doesn't really reflect the concept. As it is not aligned, and some work needs to be done on the shapes and forms. You have to look at the concept and make the shape and ratio work.

**Comment by brucelau-github** [comment] 2016-12-23 02:19
In my opinion, the logo design job should belong to the John McGivney Children's Center since this app might represent their organization and their might have their VI or logo or some principle such as colors, font.

**Comment by Blandine-AA** [comment] 2016-12-23 21:19
We are all working on the logo, including JMCC. They are also reviewing this. 

The Graphic chart of the application doesn't need to be linked to the JMCC graphic chart, but it is a good point to consider.

**Comment by stephanosm** [comment] 2016-12-23 21:23
another thought....we have discussed before not to associate any particular disability on the logo but the generic disability logo(man on a wheelchair) is a symbol used for all sorts of disabilities including old people, so I believe is not bad idea to include it as part of the logo.

**Comment by RumanaHakeem** [comment] 2016-12-24 05:39
![image](https://cloud.githubusercontent.com/assets/22264264/21465437/59b50724-c99b-11e6-87f2-5efa7d7822e2.png)

**Comment by Blandine-AA** [comment] 2016-12-24 06:10
The problem with the wheelchair is that the first impression is that the app is for people in wheelchair or with mobility disabilities. Which is not the case. I think we should get away from the wheelchair, which is most recognized symbol for mobility disabilities, but NOT ALL disabilities

**Comment by brucelau-github** [comment] 2016-12-27 18:28
![disability_symbols](https://cloud.githubusercontent.com/assets/22227484/21505751/45b36082-cc38-11e6-8f04-711f3583813e.png)
how about those pictures?

**Comment by Blandine-AA** [comment] 2016-12-30 13:32
Too similar to the [AbleRoad logo](https://ableroad.com/)

**Comment by joshi1983** [comment] 2016-12-30 21:55
The logo has been added to both app.accesslocator.com and accesslocator.com

**Comment by Blandine-AA** [comment] 2017-01-04 23:23
This is Anne's logo proposal:
![image](https://cloud.githubusercontent.com/assets/20052162/21662916/d6a5dafc-d2aa-11e6-8d59-1e58e8937abb.png)

**Comment by joshi1983** [comment] 2017-01-18 01:16
Now that we have a logo selected, do you think this issue should stay open, @Blandine-AA ?

**Comment by Blandine-AA** [comment] 2017-01-18 16:43
@joshi1983 , we haven't really closed the discussion on the subject. I guess the selected logo is here to stay for a while, at least until we have the resources to get a better one. 
So, I will close this issue for now.

**Comment by areebakamal** [comment] 2017-02-28 02:44
The svg is zipped as github doesn't support .svg files. 
[logoeditedsvg.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/805613/logoeditedsvg.zip)
Here's the png file too. 
![latest](https://cloud.githubusercontent.com/assets/23005093/23389412/d7c522d4-fd35-11e6-92dc-d652eedb11f1.png)

**Comment by joshi1983** [comment] 2017-03-14 02:51
I checked off the high res/SVG subtask in the issue description because @areebakamal provided an SVG version of the logo.

**Comment by Blandine-AA** [comment] 2017-03-24 15:15
@joshi1983 , @areebakamal , is it any work left to do on this issue? Has the svg file provided been used/implemented?

**Comment by joshi1983** [comment] 2017-03-24 16:11
As far as I know this issue is ready to close but I wanted to leave that up to @Blandine-AA.

**Comment by Blandine-AA** [comment] 2017-03-24 21:05
Ok. Closing it then !

**Closed by Blandine-AA** 2017-03-24 21:05 UTC
