### ISSUE TITLE
Demo 0.0.2 Testing: problem with release version showing in the middle of the page

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#247] opened 2017-03-07 15:43 UTC
![image](https://cloud.githubusercontent.com/assets/20052162/23664116/aa6e813e-0322-11e7-80e8-9551818a4126.png)

@joshi1983, please assign to a student as you see fits and set it to Critical.

**Comment by joshi1983** [comment] 2017-03-07 17:27
What browser are you using(Chrome, Firefox, Internet Explorer...)?

Did you thoroughly refresh your browser?  CTRL+SHIFT+R thoroughly refreshes on Chrome.

**Comment by joshi1983** [comment] 2017-03-09 03:12
The problem was actually some invalid HTML5 markup in the profile page.  I fixed this which fixed the issue's problem.

I commented that I had trouble reproducing it but only because I thought the problem would affect every page.  The problem happened in Chrome and Safari on Windows and Chrome on an Android tablet but only on the profile page.

I'm closing because I'm confident it is fixed.

**Closed by joshi1983** 2017-03-09 03:12 UTC
Labels: bug, New
