### ISSUE TITLE
User Profile : Photo upload tag visible

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#184] opened 2017-01-20 17:25 UTC
After loading my profile photo, the "Upload Your Photo" tag is still visible across my photo. Can this be removed and have maybe and 'edit' link or a camera icon in a corner to allow change of photo?
![image](https://cloud.githubusercontent.com/assets/20052162/22158685/596c6084-df0b-11e6-831b-bb7c01fa119e.png)

**Comment by joshi1983** [comment] 2017-01-20 17:36
@Blandine-AA sure.  If a user wants to remove the uploaded photo, do you have a suggestion for how to do that too?

For now, after you upload a photo once, you can replace the image but never go back to having no photo at all.

**Comment by Blandine-AA** [comment] 2017-01-21 03:55
@joshi1983, @areebakamal ,

When I look at Facebook for example, you cannot NOT have a profile picture, but the cover picture is optional. So, it can be removed.

Since, we need to have a profile picture, I believe so, what's the point to allowing a profile without picture? The main question I think is: How important is it to have a profile picture?

**Comment by stephanosm** [comment] 2017-01-21 04:31
Here's my comments on the Profile photo:
1. After uploading the image the user should be return to the Profile page. This way he can see that his photo has been uploaded, so no need for a msg that the upload is successful.
2. Profile photo is important. We will need it later on when this app turns to a social app. 
3. A good way to handle this is the following. Add an AccessLocator image (e.g. logo) as a default image in the photo area with the msg Upload your Photo. User clicks, browses computer, uploads photo, returns to Profile page. Now at the bottom right corner of the image include and "edit" button. If user wants to change this photo he can simply either (A) browse his computer for another photo, or (B) selects his gallery of stored(uploaded images) which already includes the original default AccessLocator image.

**Comment by joshi1983** [comment] 2017-01-21 14:20
I deployed the requested changes to [app.accesslocator.com](http://app.accesslocator.com).

It looks like the following after uploading the JMCC logo as a profile photo:
![image](https://cloud.githubusercontent.com/assets/11838191/22175011/96280294-dfba-11e6-9339-3a1ddeddd83c.png)


These changes are *not deployed* to [demo.accesslocator.com](http://demo.accesslocator.com) because that deployment has been locked down for demo as requested in #173.

**Comment by Blandine-AA** [comment] 2017-01-23 00:12
@joshi1983,  
I am confused about this statement... 
> These changes are not deployed to demo.accesslocator.com because that deployment has been locked down for demo as requested in #173.

I thought there were some work to be completed and have a nicer demo version released by January 31rst, as mentioned in #173 ?  When did you cut-off the demo version?

Also, as in most apps the user would expect the Edit button at the bottom right of the picture, as @stephanosm  explained in his message about the expected behavior (point 3). You have it at the bottom left. I also see that the logo implemented as the default photo.

**Comment by joshi1983** [comment] 2017-01-23 01:17
I can't be updating the demo deployment during hackathon weekend and I don't like doing things last minute so I set it up a few days ago and considered it set for the life of that demo.  There are a few side benefits to this.  Areeba doesn't have to replace screenshots down to January 31 night as features are changed.  If demo represents what we'll have testers use, test plans can be written before January 31 because the work that is under development on demo isn't changing.

The logo as a default image was requested only by @stephanosm but not confirmed by anyone else until just now by Blandine and I didn't agree that the logo was a worthwhile substitute for a profile photo.  The AccessLocator logo doesn't depict a user but the application as a whole so it doesn't fit in the same place as a profile photo.  Something like this is better as it represents a user and is already used in the home page: http://fontawesome.io/icon/user/  Is the user icon good with you guys?

You want the "Edit" right aligned instead of left-aligned?  You're fine with the "Edit" being below the uploaded photo, right?  Having it below the photo upload rectangle avoids it overlapping any portion of the photo which is why I put it there.  I aligned left because nearly all text on the profile page is aligned left.  A mock up image or sketch could help with this change.

**Comment by Blandine-AA** [comment] 2017-01-23 05:01
@joshi1983 ,

Yes, the Edit has to be below the photo. We'll make the change later, if it requires some sketchup/mockup to fix it. It is not a priority anymore. We will have to focus on finalizing more important sketches to have them implemented.

I understand that you didn't want to do changes during the hackathon week-end. We had discussed this, but I would have preferred being notified of your change of the deadline as it has some impact on my side of the work. 

Regarding the impact on Areeba's work, it is ok if there is a discrepancy between the screenshots and the app/demo. So, I wasn't expecting her to have to change the screenshots by the end of the month. What we have are good enough!

I don't like the user icon you propose, so it will have to wait until we all agree!

**Comment by joshi1983** [comment] 2017-01-23 12:47
I might be beating a dead horse with this but in case it offers any value, here's some more detail on how this misunderstanding happened on my end.  It needed to be done by January 31 and January 20 is before 31 so I didn't really change the deadline but finished earlier than you expected.  In previous discussions you mentioned the earlier a demo is available, the better.  On January 20 on #173, I wrote "Now, data saved to one won't affect the other and demo.accesslocator.com will not see the feature improvements that app.accesslocator.com gets almost immediately."  It looks like I should have made that more clear.

**Comment by Blandine-AA** [comment] 2017-01-23 13:55
Agree :)
> I wrote "Now, data saved to one won't affect the other and demo.accesslocator.com will not see the feature improvements that app.accesslocator.com gets almost immediately." It looks like I should have made that more clear.

This wasn't clear to me that the demo load was cut-off.
I guess that you will not give me a test load neither.

**Comment by joshi1983** [comment] 2017-01-23 14:29
![consensus](https://cloud.githubusercontent.com/assets/11838191/22207728/3cadca42-e14e-11e6-97e1-e28550c8fbf6.png)

I might have time to point test.accesslocator.com to the same deployment as demo.accesslocator.com this week but can't do much more than that.  That'll give you the Under Development messages that you want and the stability that you want.

**Comment by Blandine-AA** [comment] 2017-01-23 22:53
@joshi1983, you already have a lot on your late. So, don't bother with the test environment for now! As I said in another comment, I have already updated the test plan to use the demo environment, and sent it to JMCC.

If you can add the demo version number, that would be nice.

Yes, we still meet Thursday night. Hopefully @stephanosm  will make it.

I definitely agree with your time allocation this week. Thanks for the hard work :)!

**Comment by areebakamal** [comment] 2017-01-25 08:35
For the profile image, I think it should be a default user icon from font awesome any generic user avatar like
![agent-e202505f](https://cloud.githubusercontent.com/assets/23005093/22281640/14bdfc6a-e2a6-11e6-905d-2d0b9e7ad917.png)

Should display 'upload profile 
![upload button](https://cloud.githubusercontent.com/assets/23005093/22282217/084fa570-e2a9-11e6-84d7-2d1edee72c0f.jpg)

When you hover your mouse over it, the button should darken (button depicted here as circle, but it can be a horizontal rectangle or a big square etc)  
![userprofileuploadicon](https://cloud.githubusercontent.com/assets/23005093/22282771/71b4e892-e2ac-11e6-900f-6de13a3a5976.jpg)

Then window opens with your computer files to choose from. 
After uploading the page should auto refresh and display the profile with the updated photo. 

Remove photo option should be there in my opinion. It can be a rectangle button 'remove photo' that appears towards the bottom of the photo once you hover your mouse over the picture. After user deletes photo, then again the same default user avatar appears.

**Comment by stephanosm** [comment] 2017-01-25 16:44
I agree, but remember the 'hover' behavior should be different for mobile
devices.

**Comment by joshi1983** [comment] 2017-02-04 21:39
I like Areeba's comments and mockups.  Does this work seem good for someone to work on, @Blandine-AA ?  @areebakamal might you want to take on your suggested changes?

**Comment by joshi1983** [comment] 2017-02-04 21:41
I unassigned myself because I didn't touch the photo upload feature in over a week and it might be good for someone else to pick up as I focus on the data importing and some internal changes needed for the new location rating feature.

**Comment by joshi1983** [comment] 2017-02-08 04:09
I assigned to @areebakamal because it seemed like she was interested in taking this on.  She'll start by:
1. Making the default profile photo a user icon.
1. After finishing that, she'll work on making the file selection dialog pop up immediately after the user clicks the "Upload Profile Photo" link instead of its current redirect to a dedicated page for uploading a profile photo.

**Comment by joshi1983** [comment] 2017-02-20 00:29
The user icon was added when there is no photo uploaded.  @areebakamal is continuing work to improve how the photo uploading can be started without leaving the profile page.

**Comment by joshi1983** [comment] 2017-02-23 09:38
I added some review comments to your pull request #231, @areebakamal.

**Comment by Blandine-AA** [comment] 2017-03-07 15:26
@baseer110, please test this feature today if  possible. Thanks!

**Comment by baseer110** [comment] 2017-03-17 17:44
I have checked the feature, I am able to upload the profile picture and when I upload the photo the page gets auto refresh and display the profile with the updated photo.

![image](https://cloud.githubusercontent.com/assets/4041079/24055481/8b29b77a-0b16-11e7-89e1-c3aeb5109563.png)

But I have some points to add here is that,  if I am as a user wants to delete my profile photo so how can I do it cause I did not see any link to delete the uploaded image. 

Also, If I try to upload photo size of say 4MB I am redirected to other page below shown: 

![image](https://cloud.githubusercontent.com/assets/4041079/24055706/7ff15038-0b17-11e7-9118-ac0f5de34b1a.png)

I didn't see the any message stating the how much size of photo I can be able to upload in profile.

Other wise the feature working fine, after uploading the photo the page gets auto refresh and I can see the updated photo.

**Comment by Blandine-AA** [comment] 2017-03-17 18:09
@baseer110 , good catch for trying a large size photo. I agree with your proposal to review this at tonight meeting with @joshi1983 .

My suggestion is to limit the photo size and to have a check before loading the photo.  So the user knows ahead of time if his photo meets the size criteria.

**Comment by Blandine-AA** [comment] 2017-03-18 01:44
@baseer110 , since @joshi1983 has opened a new issue to track the large file upload error, please update this issue and follow the process to close it.

**Comment by baseer110** [comment] 2017-03-20 22:45
As there is another ticket for this issue therefore closing this ticket

**Closed** 2017-03-20 22:47 UTC
Labels: Ready for testing
