### ISSUE TITLE
Sign Up: prevent confirmation email to end up in Trash or Spam folders

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#520] opened 2018-03-01 20:28 UTC
When signing up by filling in first name, last name, a password... an email is sent to the specified email address which contains a link which must be clicked before the new account can be used. The email is getting filtered as SPAM or Trash in gmail and hotmail.

Due to time constraint, a workaround has been implemented in 0.0.5 as part of  #275, that also explains the proper solution.

Implementation of the proper solution is therefore postponed to a later release.

**Comment by joshi1983** [comment] 2018-06-04 01:34
@stephanosm is having a bigger problem where he doesn't receive the emails at all in his gmail and uwindsor accounts.

**Comment by passionInfinite** [comment] 2018-06-20 20:02
@joshi1983 Assign this to me. I will sort it out

**Comment by joshi1983** [comment] 2018-06-20 22:20
Sure.  You're assigned.  

I'll make a pull request so you see what I've done so far with it.  I have a change that switches to relying on gmail for sending email.  It works quite well but with some minor weaknesses that would ideally be avoided:
- It exposes a gmail account password in plain text in the .env file.  The file would be accessible only to trusted people, anyway, but it would be nicer to not expose it.
- Sending from "noreply@accesslocator.com" needs to be tested.  I'd still need to experiment to see if setting the FROM address to something other than the authenticated gmail account would cause some email clients to filter its email as SPAM.

**Comment by singlaneha2205** [comment] 2018-07-03 15:28
I tried to sign up for the application but I have not received any email with the confirmation code at all not even in the spam  folder.

Thanks and Regards,
Neha Singla

**Comment by passionInfinite** [comment] 2018-07-03 15:30
I just checked in and I got the email. I checked it twice. Are you sure you
entered the right email?

**Comment by singlaneha2205** [comment] 2018-07-03 15:41
Yes, I checked it again with two different mail ids and did not receive the
mail on any of them.

**Comment by passionInfinite** [comment] 2018-07-03 15:53
Can you send me the domain(url) on which you are signing up.

**Comment by singlaneha2205** [comment] 2018-07-03 16:08
I tried signing up on these two URLs.

http://demo.accesslocator.com/signup
https://app.accesslocator.com/signup

**Comment by passionInfinite** [comment] 2018-07-03 17:38
Okay! So @joshi1983 It means our code is not deployed on the server. I will update the servers.

**Comment by joshi1983** [comment] 2018-07-04 10:45
I'm commenting on @passionInfinite 's behalf.  He told me that app.accesslocator.com is ready for you to try again, @singlaneha2205 .

**Comment by passionInfinite** [comment] 2018-07-04 17:57
@singlaneha2205 you will have the option of resend verification mail again soon!

**Comment by passionInfinite** [comment] 2018-07-05 06:56
@joshi1983 This should not be marked as failed testing. As our code is right.

**Comment by joshi1983** [comment] 2018-07-05 11:05
@passionInfinite I just didn't see @singlaneha2205's comment until now.  Thanks for pointing that out and I removed the label.

@singlaneha2205 do you see a gears icon next to labels like this?
![image](https://user-images.githubusercontent.com/11838191/42319952-9c4ed2a2-8021-11e8-88cf-7be30cf61b8f.png)

It would be nice if @singlaneha2205 can add The Failing Testing label when she finds an issue that was labeled "Ready for testing" still has a problem in it.

**Comment by joshi1983** [comment] 2018-07-05 11:08
I'm closing the issue as it has been tested by someone who reproduced the original problem.  It is fixed in app.accesslocator.com but not in demo.accesslocator.com until next release.

**Closed by joshi1983** 2018-07-05 11:08 UTC
Labels: Design

**Comment by singlaneha2205** [comment] 2018-07-05 16:12
@joshi1983 I checked I do not see any gears sign next to labels. Is this
due to access rights?

**Comment by joshi1983** [comment] 2018-07-05 16:56
@singlaneha2205 yes it was related to access rights.  I increased your permissions so you should be able to edit an issue's labels now.  Let me know if I'm wrong.
